name: joinmun
description: A new Flutter project.



dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.7.2
  uri: ^0.11.3
  url_launcher: ^4.0.1
  sticky_headers: ^0.1.7
  intl: ^0.15.7
  flutter_webview_plugin: ^0.2.1+2
  flutter_staggered_grid_view: "^0.2.2"
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dependency_overrides:
  quiver: ^2.0.0+1



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/avatar_placeholder.png
    - assets/committee.jpg
    - assets/social-night.jpg
    - assets/opening-ceremony.jpg
    - assets/closing-ceremony.jpg
    - assets/cultural-trip.jpg
    - assets/banner.png
    - assets/photo.png
    - assets/lost.png
    - assets/bicycle.png
    - assets/ic_fb_white.png
    - assets/ic_twitter_white.png
    - assets/ic_ig_white.png
    - assets/totebag.png
    - assets/trump.png
    - assets/shirt.png
    - assets/shirt2.png
    - assets/shirt3.png
    - assets/shirt4.png
    - assets/bg.jpg
    - assets/fakhri.png
    - assets/carol.jpg
    - assets/ic_fb.png
    - assets/ic_twitter.png
    - assets/ic_ig.png
    - assets/ic_bus.png
    - assets/ic_taxi.png
    - assets/ic_place_orange_24.png
    - assets/ic_train_orange_24.png
    - assets/ic_googlemap.png
    - assets/nothing_here.png
    - assets/img_drawer_header.png
    


  fonts:
    - family: CenturyGothic
      fonts:
        - asset: fonts/CenturyGothicRegular.ttf
          weight: 500
    - family: LemonMilk
      fonts:
        - asset: fonts/LemonMilk.otf
          weight: 500
        - asset: fonts/LemonMilklight.otf
          weight: 300
        - asset: fonts/LemonMilkbold.otf
          weight: 700
    - family: League Spartan
      fonts:
        - asset: fonts/LeagueSpartan-Bold.otf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
